name: Publish docker images

on:
  push:
    branches:
      - master

jobs:

  publish:
    runs-on: [self-hosted]

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show me what you got
        env:
          CI_REF: '${{github.ref}}'
        run: |
          echo "Changes found:"
          .github/change-finder.sh
          echo "Dockerfiles found:"
          .github/change-finder.sh | .github/dockerfile-filter.sh
      - name: Build and publish
        env:
          CI_REF:                '${{github.ref}}'
          TAG_NAME:              'g${{github.run_number}}'
          REGISTRY_URL:          'docker.tw.ee'
          DEPLOY_USERNAME:       '${{ secrets.DEPLOY_USERNAME }}'
          DEPLOY_PASSWORD:       '${{ secrets.DEPLOY_PASSWORD }}'
        run: |
            echo $CI_REF
            for REPO in $(.github/change-finder.sh | .github/dockerfile-filter.sh); do
                .github/docker-publish.sh $REPO $TAG_NAME
                .circleci/github-publish.sh $REPO $TAG_NAME
            done
